language: cpp

# Scons automagically installs Mitsuba
install: true

# Only build the latest and greatest
git:
  depth: 1

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      # Avoid downloading again - see https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      before_install:
        # Travis needs to reload ruby before continuing - see https://github.com/travis-ci/travis-ci/issues/8552
        - brew update
        - brew install qt scons collada-dom
        - git clone https://github.com/mitsuba-renderer/dependencies_macos dependencies --depth=1
        # Let SCons see brewed Qt (for the utils) - and they go last to avoid interfering with Travis cache
        - export PATH="$PATH:/usr/local/opt/qt/bin"
        # Print XCode SDK path
        - xcrun --show-sdk-path
      script:
        - scons -j1 --cfg=build/config-macos10.12-clang-x86_64-travis.py --debug=stacktrace
      after_failure:
        # Poor man's send to S3
        - cat config.log
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            # See manual, doc/compiling.tex
            - libpng12-dev
            - libjpeg-dev
            - libilmbase-dev
            - libxerces-c-dev
            - libboost-all-dev
            - libopenexr-dev
            - libglewmx-dev
            - libxxf86vm-dev
            - libeigen3-dev
            - libfftw3-dev
            # not available on trusty - xenial and up
            # - libcollada-dom-dev
            - qt5-default
            - libqt5opengl5-dev
            - libqt5xmlpatterns5-dev
      before_install:
        # Travis doesn't obey the `python` key when the project isn't pythonesque
        - pyenv install 3.6.2
        - pyenv local 3.6.2
        - pip install -U setuptools
        - pip install wheel
        - pip install scons
        - scons --version
      script:
        # More than 1 job crashes travis when building python bindings
        scons -j1 --cfg=build/config-linux-gcc-debug.py --debug=stacktrace
